# Site
repository: luckydoyun/luckydoyun.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ì¥ë„ìœ¤
title: í’€ìŠ¤íƒ ì—”ì§€ë‹ˆì–´
email: doyun.jang.0128@gmail.com
website: https://github.com/luckydoyun/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  luckydoyun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ddoyun.j
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ê³µê³µê¸°ê´€ ëŒ€í˜• SI/SM í”„ë¡œì íŠ¸ì—ì„œ <mark>ë‹¤ì–‘í•œ ì—…ë¬´</mark>ë¥¼ ê²½í—˜í•œ 4ë…„ì°¨ í’€ìŠ¤íƒ ê°œë°œìì…ë‹ˆë‹¤.<br>
  SMí”„ë¡œì íŠ¸ì—ì„œ ìš”êµ¬ì‚¬í•­ì— ë§ì¶° UIì œì‘(í”„ë¡ íŠ¸)ê³¼ ë¹„ì§€ë‹ˆìŠ¤ ë¡œì§ ê°œë°œ ë° ëª¨ë¸ë§ ì„¤ê³„(ë°±ì—”ë“œ)ë¥¼ ê²½í—˜í•˜ì˜€ê³ ,<br>
  SIí”„ë¡œì íŠ¸ì—ì„œëŠ” ê°œë°œì„œë²„ ë° ë¹Œë“œë°°í¬ í™˜ê²½ì„ êµ¬ì¶•í•˜ì—¬ ê°œë°œìë“¤ì´ ê°œë°œí•  ìˆ˜ ìˆëŠ” í™˜ê²½ì„ ë§Œë“  ê²½í—˜ì„ í–ˆìŠµë‹ˆë‹¤.<br>

  <br>ë‹¤ì–‘í•œ ì§ë¬´ë¡œ ë‚˜ë‰˜ì–´ì§„ ITì—ì„œ <mark>ì˜ì‚¬ì†Œí†µ</mark>ê³¼ <mark>ê³µê°ëŠ¥ë ¥</mark>ì€ ë¬´ì—‡ë³´ë‹¤ ì¤‘ìš”í•˜ë‹¤ê³  ìƒê°í•©ë‹ˆë‹¤.<br>
  ê·¸ë˜ì„œ ë‹¤ë¥¸ ì§ë¬´ì˜ êµ¬ì„±ì›ê³¼ <mark>í˜‘ì—…</mark>ì‹œ ìš”êµ¬ì‚¬í•­ì„ ì •í™•íˆ ì´í•´í•˜ê³  ì „ë‹¬í•˜ëŠ” ì—­ëŸ‰ì„ ìŒ“ì•„ì™”ìŠµë‹ˆë‹¤.<br>

  <br><mark>íš¨ìœ¨ì ìœ¼ë¡œ ì¼í•˜ëŠ” ë°©ë²•</mark>ì— ëŒ€í•´ ìƒê°í•˜ëŠ” ê²ƒì„ ì¢‹ì•„í•˜ë©°, ë°˜ë³µë˜ëŠ” ì‘ì—…ì„ ìë™í™”í•˜ì—¬ ì—…ë¬´ ì‹œê°„ì„ 60ë¶„ì—ì„œ <strong>20ë¶„</strong>ìœ¼ë¡œ ì¤„ì˜€ë˜ ê²½í—˜ì´ ìˆìŠµë‹ˆë‹¤.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: í¼ì¦ì—ì´ì•„ì´
        link: https://puzzle-ai.io/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: 2023.05 ~
        quote: >
          ì˜ë£Œ AI ìŒì„±ì¸ì‹ ì„œë¹„ìŠ¤ ê³ ë„í™”
        description: | # this will include new lines to allow paragraphs
            - ì„œë¹„ìŠ¤ ê³ ë„í™”ë¥¼ ìœ„í•œ DBëª¨ë¸ë§ ì„¤ê³„
            - DBêµì²´ë¡œ ì´í•œ ë°ì´í„° ì´ê´€(MySQL -> postgreSQL)
            - Jupyter Notebookë¥¼ í™œìš©í•˜ì—¬ ë¹„ì •í˜• ë°ì´í„° ê°€ê³µ ë° DBì ì¬
            - ì—¬ëŸ¬ íŒ€ë“¤ì˜ ì˜ì‚¬ì†Œí†µì„ ìœ„í•œ ì‚¬ë‚´ ë°ì´í„° ì‚¬ì „ ìƒì„±
      
      - title: ìŒìš©ì •ë³´í†µì‹ (ì£¼)
        link: https://www.sicc.co.kr/
        # link_text: boringcompany.com
        sub_title: Software Architect(AA)
        caption: 2022.01 - 2022.08
        quote: >
          êµ­ì„¸ì²­ ê¸ˆìœµíˆ¬ìì†Œë“ì„¸ ì „ì‚°ì‹œìŠ¤í…œ ê°œë°œ
        description: | # this will include new lines to allow paragraphs
            - ê¸ˆìœµíˆ¬ìì†Œë“ì„¸ ì „ì‚°ì‹œìŠ¤í…œ SI í”„ë¡œì íŠ¸ ì°¸ì—¬
            - í”„ë¡œì íŠ¸ ê°œë°œì„œë²„ ë¹Œë“œ&ë°°í¬ ìë™í™”ë¥¼ ìœ„í•´ ìŠ¤ì¼€ì¤„ ì„¤ì •(crontab)
            - ë¹Œë“œë°°í¬ì˜ ì˜¤ë¥˜ë¥¼ ìµœì†Œí™” í•˜ê¸° ìœ„í•´ í”„ë¡œì íŠ¸ ê°œë°œì ëŒ€ìƒìœ¼ë¡œ ë¹Œë“œë°°í¬ ì»¨ë²¤ì…˜ì— ê´€í•œ êµìœ¡ ì§„í–‰
            - ê°œë°œììš”ì²­ìœ¼ë¡œ POIë¼ì´ë¸ŒëŸ¬ë¦¬(ì—‘ì…€) ì»¤ìŠ¤í…€ë§ˆì´ì§•

      - title: ì•„ì´í‹°ì„¼
        link: http://www.itcen.co.kr/
        # link_text: boringcompany.com
        sub_title: Software Architect(DA)
        caption: 2020.01 - 2021.12
        quote: >
          ì°¨ì„¸ëŒ€ êµ­ì„¸í–‰ì •ì‹œìŠ¤í…œ ìš´ì˜ ë° ìœ ì§€ë³´ìˆ˜ ì‚¬ì—…
        description: | # this will include new lines to allow paragraphs
            - ì°¨ì„¸ëŒ€ êµ­ì„¸í–‰ì •ì‹œìŠ¤í…œ SM í”„ë¡œì íŠ¸ ì°¸ì—¬
            - í”„ë¡œì íŠ¸ ë©”íƒ€(í‘œì¤€ë‹¨ì–´, í‘œì¤€ìš©ì–´, í‘œì¤€ë„ë©”ì¸, DBëª¨ë¸ë§) ê´€ë¦¬
            - ê°œë°œíŒ€ì˜ ì‹ ê·œ ìš”êµ¬ì‚¬í•­ ë° ê°œë°œ ì˜í–¥ë„ë¥¼ ë¶„ì„í•˜ì—¬ ì í•©í•œ ëª¨ë¸ë§ ì œì‹œ
            - DA#(ëª¨ë¸ë§ íˆ´)ì„ ì‚¬ìš©í•˜ê¸° ìœ„í•œ ì˜¤ë¼í´DB ì„¤ì¹˜ ë° í…ŒìŠ¤íŠ¸ ê°€ì´ë“œ ì œì‘
            - í”„ë¡œì íŠ¸ ë©”íƒ€ í’ˆì§ˆ ì ê²€ ì—…ë¬´ë¥¼ Shell Scriptë¡œ ìë™í™”í•˜ì—¬ ì—…ë¬´ ì‹œê°„ <strong>75%</strong> ë‹¨ì¶•
      
      - title: ì•„ì´í‹°ì„¼
        link: http://www.itcen.co.kr/
        # link_text: boringcompany.com
        sub_title: Full-Stack Developer
        caption: 2019.01 - 2019.12
        quote: >
          ì°¨ì„¸ëŒ€ êµ­ì„¸í–‰ì •ì‹œìŠ¤í…œ ìš´ì˜ ë° ìœ ì§€ë³´ìˆ˜ ì‚¬ì—…
        description: | # this will include new lines to allow paragraphs
            - ì°¨ì„¸ëŒ€ êµ­ì„¸í–‰ì •ì‹œìŠ¤í…œ SM í”„ë¡œì íŠ¸ ì°¸ì—¬
            - MVC íŒ¨í„´ì„ í™œìš©í•˜ì—¬ ì‹œìŠ¤í…œ ìœ ì§€ë³´ìˆ˜ ë° ê°œë°œ
            - ì „ìì •ë¶€ í”„ë ˆì„ì›Œí¬, Oracle, DB2 í™˜ê²½ì—ì„œì˜ ê°œë°œ ê²½í—˜
            - 365ì¼ ë¬´ì¤‘ë‹¨ ì‹œìŠ¤í…œì—ì„œ ë¹Œë“œ&ë°°í¬ ë° í…ŒìŠ¤íŠ¸ ê²½í—˜
            - ì‹ ê·œ íŒ€ì›ì´ í”„ë¡œì íŠ¸ ê°œë°œ ë¬¸í™”ì— ì ì‘í•˜ë„ë¡ ì˜¨ë³´ë”© í”„ë¡œì„¸ìŠ¤ ê°€ì´ë“œ ë¬¸ì„œ ì‘ì„±


  - title: Competency # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ê°œë°œ íŒŒíŠ¸
        # link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
         #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <mark>ëŒ€í˜• í”„ë¡œì íŠ¸ ê°œë°œ ê²½í—˜ ë° ì†Œìˆ˜ íŒ€ í”„ë¡œì íŠ¸ ë¦¬ë“œ ê²½í—˜</mark>
        description: | # this will include new lines to allow paragraphs
          - ë©‹ìŸì´ì‚¬ì í”„ë¡ íŠ¸ì—”íŠ¸ ìŠ¤ì¿¨4ê¸° Final Project ë¦¬ë“œ (2023.02 - 2023.03)
          - ì°¨ì„¸ëŒ€ êµ­ì„¸í–‰ì • ì‹œìŠ¤í…œ í¬í„¸ ê°œë°œ ë° ê´€ë¦¬ (2019.01 - 2019.12)
      
      - layout: top-middle
        title: ì»´í“¨í„° ì†Œí”„íŠ¸ì›¨ì–´ ê°œë°œì˜ ëª¨ë“  ê³„ì¸µ ì¹œìˆ™
        quote: >
          <mark>ì†Œí”„íŠ¸ì›¨ì–´ì˜ ì „ë°˜ì ì¸ ì›ë¦¬ë¥¼ ì´í•´í•˜ê³  ìˆìœ¼ë©° ITì˜ ëª¨ë“  ê³³ì—ì„œ í˜‘ë ¥ ê°€ëŠ¥</mark>
        description: | # this will include new lines to allow paragraphs
          - Git, Githubì„ í™œìš©í•˜ì—¬ ì†Œê·œëª¨ í”„ë¡œì íŠ¸ ê²½í—˜ (2023.01 - 2023.03)
          - CI/CD êµ¬ì¶• ê²½í—˜ (2022.01 - 2022.08)
          - SQL íŠœë‹ì„ í†µí•œ ë°°ì¹˜ ì„œë²„ ë¶€í•˜ ê°œì„  (2020.01 - 2020.12)
          - Java, DB2ë¥¼ í™œìš©í•˜ì—¬ ë¹„ì¦ˆë‹ˆìŠ¤ ë¡œì§ êµ¬í˜„ (2019.01 - 2019.12)
          - UI í”„ë ˆì„ì›Œí¬ë¥¼ í™œìš©í•˜ì—¬ UI ì œì‘ (2019.01 - 2019.12)
          - ì»´í“¨í„°ê³µí•™ê³¼ ì¡¸ì—… (2010.03 - 2017.08)
      
      - layout: top-middle
        title: í­ ë„“ì€ ì»¤ë®¤ë‹ˆì¼€ì´ì…˜ ëŠ¥ë ¥
        quote: >
          <mark>ë‹¤ì–‘í•œ ì§ë¬´ê²½í—˜ìœ¼ë¡œ ë‹¤ì–‘í•œ ITì§ë¬´ì— ëŒ€í•œ ì´í•´ë„ ë†’ìŒ</mark>
        description: | # this will include new lines to allow paragraphs
          - ë°±ì—”ë“œ ê°œë°œ
          - í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œ
          - DevOps
          - DA
          - DBA

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TECHIT
        caption: 2022.11 - 2023.03
        sub_title: ë©‹ìŸì´ì‚¬ì í”„ë¡ íŠ¸ì—”ë“œìŠ¤ì¿¨ 4ê¸°
        quote: >
          <mark>Front-End Developer ê¸°ë³¸ ê°œë… êµìœ¡</mark>
        description: | # this will include new lines to allow paragraphs
          - Git ë²„ì „ ê´€ë¦¬ êµìœ¡
          - HTML5, CSS3, JavaScript êµìœ¡
          - React êµìœ¡ ë° React í”„ë¡œì íŠ¸

      - layout: left
        title: ITWILL
        caption: 2022.11 - 2023.03
        sub_title: ì˜¤ë¼í´ ë°ì´í„°ë² ì´ìŠ¤ë¥¼ í™œìš©í•œ ì¸í”„ë¼ìŠ¤íŠ¸ëŸ­ì²˜ ì „ë¬¸ê°€ ì–‘ì„±ê³¼ì •
        quote: >
          <mark>DB ì—”ì§€ë‹ˆì–´ë§ ê¸°ë³¸ ê°œë… êµìœ¡</mark>
        description: | # this will include new lines to allow paragraphs
          - ì˜¤ë¼í´ DBMS êµìœ¡
          - ì¸ë±ìŠ¤, ì‹¤í–‰ ê³„íš, RDBMSì˜ êµ¬ì¡°
          - SQL íŠœë‹ ê¸°ë³¸ êµìœ¡

      - layout: left
        title: ì»´í“¨í„°ê³µí•™ê³¼
        caption: 2010.03 - 2017.08
        sub_title: ì¶©ë‚¨ëŒ€í•™êµ ì»´í“¨í„°ê³µí•™ê³¼ ì¡¸ì—…
        quote: >
          <mark>ì»´í“¨í„°ê³µí•™ì— ëŒ€í•œ ì „ë°˜ì ì¸ í•™ì‚¬êµìœ¡</mark>
        description: | # this will include new lines to allow paragraphs
          - ì»´í“¨í„°í”„ë¡œê·¸ë˜ë°(C, Java)
          - ì•Œê³ ë¦¬ì¦˜ & ìë£Œêµ¬ì¡°
          - ì´ì‚°ìˆ˜í•™ê³¼ í™•ë¥  ë° í†µê³„
          - í”„ë¡œê·¸ë˜ë°ì–¸ì–´ê³¼ ì»´í“¨í„°ê³µí•™ê°œë¡  ë° ì†Œí”„íŠ¸ì›¨ì–´ê³µí•™
          - ë°ì´í„°ë² ì´ìŠ¤ ë° ë°ì´í„°ë² ì´ìŠ¤ ì‹¤ìŠµ
          - ì»´í“¨í„°êµ¬ì¡°ì™€ ë°ì´í„°í†µì‹ 

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          <mark>ì—…ë¬´ ë˜ëŠ” êµìœ¡ì—ì„œ ì‚¬ìš©í–ˆë˜ ê¸°ìˆ ì…ë‹ˆë‹¤.</makr>
      - layout: left
        title: BACK-END
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - Java
            - Python
            - Spring MVC

      - layout: left
        title: FRONT-END
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - ES6
            - HTML5, CSS
            - React

      - layout: left
        title: DevOps
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - Oracle, DB2
            - SQL
            - Docker
            - Linux
            - Github
            - Slack
            - Notion
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ì·¨ë¯¸ í™œë™
      - ê±´ê°• ë° ê·¼ë ¥ì„ ìœ„í•œ í—¬ìŠ¤&ë¼ì´ë”©ğŸ‹ğŸ»
      - ì¢‹ì€ê³µê¸° ë§ˆì‹œëŸ¬ ë“±ì‚°ğŸŒ„
      - ITë¸”ë¡œê·¸ ìš´ì˜ìœ¼ë¡œ ì§€ì†ì ì¸ ê³µë¶€ğŸ§
      - ë¹µğŸ¥ ë¨¹ìœ¼ëŸ¬ ì¹´í˜ê°€ê¸°

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

github: [metadata]
