# Site
repository: luckydoyun/luckydoyun.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 장도윤
title: 풀스택 엔지니어
email: doyun.jang.0128@gmail.com
website: https://github.com/luckydoyun/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  luckydoyun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ddoyun.j
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  공공기관 대형 SI/SM 프로젝트에서 다양한 업무를 경험한 4년차 풀스택 개발자입니다.
  SM프로젝트에서는 요구사항에 맞춰 UI제작(프론트)과 비지니스 로직 개발 및 모델링 설계(백엔드) 경험하였고
  SI프로젝트에서는 개발서버 구축 및 빌드배포 환경을 구축하여 개발자들이 개발할 수 있는 환경을 만든 경험이 있습니다.

  다양한 직무로 나뉘어진 IT에서 <mark>의사소통</mark>과 <mark>공감능력</mark>은 무엇보다 중요하다고 생각합니다.
  다른 직무의 구성원들과 <mark>'함께'</mark> 문제를 해결해야할 때 정확하게 이해할 수 있도록 표현하는 역량을 쌓고자 노력해왔습니다.

  효율적으로 일하는 방법에 대해 생각하는 것을 좋아하며, 반복되는 배치작업을 자동화하여 작업시간을 <strong>66%</strong> 줄였던 경험이 있습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 쌍용정보통신(주)
        link: https://www.sicc.co.kr/
        # link_text: boringcompany.com
        sub_title: Software Architect(AA)
        caption: 2022.01 - 2022.08
        quote: >
          국세청 금융투자소득세 전산시스템 개발
        description: | # this will include new lines to allow paragraphs
            - 금융투자소득세 전산시스템 SI 프로젝트 참여
            - 개발서버 & 빌드/배포 환경 구축 1인 담당
            - 개발서버 관리 및 프로젝트 개발 트러블슈팅 1인 담당

      - title: 아이티센
        link: http://www.itcen.co.kr/
        # link_text: boringcompany.com
        sub_title: Software Architect(DA)
        caption: 2020.01 - 2021.12
        quote: >
          차세대 국세행정시스템 운영 및 유지보수 사업
        description: | # this will include new lines to allow paragraphs
            - 차세대 국세행정시스템 SM 프로젝트 참여
            - 프로젝트 메타(표준단어, 표준용어, 표준도메인, DB모델링) 관리
            - DA#(모델링 툴)을 사용하기 위한 오라클DB 설치 및 테스트 가이드 제작
            - 프로젝트 메타 품질 체크 업무를 자동화하여 업무 시간 <strong>66% 단축</strong>
      
      - title: 아이티센
        link: http://www.itcen.co.kr/
        # link_text: boringcompany.com
        sub_title: Full-Stack Developer
        caption: 2019.01 - 2019.12
        quote: >
          차세대 국세행정시스템 운영 및 유지보수 사업
        description: | # this will include new lines to allow paragraphs
            - 차세대 국세행정시스템 SM 프로젝트 참여
            - MVC 패턴을 활용하여 시스템 유지보수 및 개발
            - 전자정부 프레임워크, Oracle, DB2 환경에서의 개발 경험
            - 365일 무중단 시스템에서 운영서버 전체 빌드/배포 및 백업 담당 경험


  - title: Competency # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 개발 파트
        # link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
         #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <mark>대형 프로젝트 개발 경험 및 소수 팀 프로젝트 리드 경험</mark>
        description: | # this will include new lines to allow paragraphs
          - 멋쟁이사자 프론트엔트 스쿨4기 Final Project 리드 (2023.02 - 2023.03)
          - 차세대 국세행정 시스템 포털 개발 및 관리 (2019.01 - 2019.12)
      
      - layout: top-middle
        title: 컴퓨터 소프트웨어 개발의 모든 계층 친숙
        quote: >
          <mark>소프트웨어의 전반적인 원리를 이해하고 있으며 IT의 모든 곳에서 협력 가능</mark>
        description: | # this will include new lines to allow paragraphs
          - Git, Github을 활용하여 소규모 프로젝트 경험 (2023.01 - 2023.03)
          - CI/CD 구축 경험 (2022.01 - 2022.08)
          - SQL 튜닝을 통한 배치 서버 부하 개선 (2020.01 - 2020.12)
          - 데이터베이스와 요구사항을 바탕으로 비즈니스 로직 구현 (2019.01 - 2019.12)
          - UI 프레임워크를 활용하여 UI 제작 (2019.01 - 2019.12)
          - 컴퓨터공학과 졸업 (2010.03 - 2017.08)
      
      - layout: top-middle
        title: 폭 넓은 커뮤니케이션 능력
        quote: >
          <mark>다양한 직무경험으로 다양한 IT직무에 대한 이해도 높음</mark>
        description: | # this will include new lines to allow paragraphs
          - 백엔드 개발
          - 프론트엔드 개발
          - DevOps
          - DA
          - DBA
          - AA

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TECHIT
        caption: 2022.11 - 2023.03
        sub_title: 멋쟁이사자 프론트엔드스쿨 4기
        quote: >
          <mark>Front-End Developer 기본 개념 교육</mark>
        description: | # this will include new lines to allow paragraphs
          - Git 버전 관리 교육
          - HTML5, CSS3, JavaScript 교육
          - React 교육 및 React 프로젝트

      - layout: left
        title: ITWILL
        caption: 2022.11 - 2023.03
        sub_title: 오라클 데이터베이스를 활용한 인프라스트럭처 전문가 양성과정
        quote: >
          <mark>DB 엔지니어링 기본 개념 교육</mark>
        description: | # this will include new lines to allow paragraphs
          - 오라클 DBMS 교육
          - 인덱스, 실행 계획, RDBMS의 구조
          - SQL 튜닝 기본 교육

      - layout: left
        title: 컴퓨터공학과
        caption: 2010.03 - 2017.08
        sub_title: 충남대학교 컴퓨터공학과 졸업
        quote: >
          <mark>컴퓨터공학에 대한 전반적인 학사교육</mark>
        description: | # this will include new lines to allow paragraphs
          - 컴퓨터프로그래밍(C, Java)
          - 알고리즘 & 자료구조
          - 이산수학과 확률 및 통계
          - 프로그래밍언어과 컴퓨터공학개론 및 소프트웨어공학
          - 데이터베이스 및 데이터베이스 실습
          - 컴퓨터구조와 데이터통신

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          <mark>업무 또는 교육에서 사용했던 기술입니다.</makr>
      - layout: left
        title: BACK-END
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - Java
            - Spring MVC, Spring
            - Maven
            - Eclipse, Visual Studio Code

      - layout: left
        title: FRONT-END
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - ES6
            - Npm, Vite
            - HTML5, CSS
            - React

      - layout: left
        title: DevOps
        # sub_title: -
        # caption: -
        description: | # this will include new lines to allow paragraphs
            - Oracle, DB2
            - DA#
            - Jenkins
            - Tomcat
            - Linux
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      취미 활동
      - 건강 및 근력을 위한 헬스
      - 좋은공기 마시러 등산
      - RPG 게임
      - 빵 먹으러 카페가기

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

github: [metadata]
